config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'home#index'

  get "/what" => "home#what"

  resources :charges

  resources :parking_events

  resources :customers

  resources :payments

end

app/models/lot.rb
class Lot < ActiveRecord::Base
  has_many :parking_events

  geocoded_by :address
  after_validation :geocode


  def availability
    self.capacity - self.parking_events.where(time_out: nil).count
  end
end

app/models/parking_event.rb
class ParkingEvent < ActiveRecord::Base
  mount_uploader :photo_in, PhotoInUploader
  mount_uploader :photo_out, PhotoOutUploader
  belongs_to :lot
  belongs_to :user

  delegate :rate, to: :lot, prefix: true
  delegate :address, to: :lot
  delegate :customer_id, to: :user

  def populate_duration
    self.duration = self.time_out - self.time_in
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_reader :card_number, :expiry_date, :expiry_date, :cvc

  has_many :parking_events, dependent: :nullify

  validates :license, uniqueness: true

  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}".strip
    else
      email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private 

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name]
    devise_parameter_sanitizer.for(:account_update) << [:first_name]
    devise_parameter_sanitizer.for(:sign_up) << [:last_name]
    devise_parameter_sanitizer.for(:account_update) << [:last_name]
    devise_parameter_sanitizer.for(:sign_up) << [:license]
    devise_parameter_sanitizer.for(:account_update) << [:license]
    devise_parameter_sanitizer.for(:sign_up) << [:customer_id]
    devise_parameter_sanitizer.for(:account_update) << [:customer_id]

  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @lots = Lot.all
    @hash = Gmaps4rails.build_markers(@lots) do |lot, marker|
      marker.lat lot.latitude
      marker.lng lot.longitude
      marker.infowindow "<p>Lot Address: #{lot.address}</p> <p>Available Stalls: #{lot.availability}</p> <p>Parking Rate: $#{((lot.rate*60*60).round)/100}/hour</p>"
    end
  end
end

app/controllers/parking_events_controller.rb
class ParkingEventsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    populate_new_event

    @parking_event = ParkingEvent::SearchForExistingEvent.new( new_event: @new_event )
  end

  def new
    @parking_event = ParkingEvent.new
  end

  private

  def populate_new_event
    @new_event = ParkingEvent.new parking_event_params
    @new_event.time_in ||= Time.now
    @new_event.lot_id ||= 1
    @new_event.license = parse_license(parking_event_params[:photo_in].tempfile.path)
  end

  def parking_event_params
    params.require(:parking_event).permit(:lot_id, :photo_in, :time_in)
  end

  def parse_license(license_path)
    e = Tesseract::Engine.new {|e|
      e.language  = :eng
      e.blacklist = '|'
    }
    e.text_for(license_path).strip
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @license = params[:license]
    @parking_events = ParkingEvent.where("license = ?", @license).where(stripe_txn_id: nil).where("time_out IS NOT ?", nil)
    @total = 0
    @parking_events.each do |parking_event|
      @total += parking_event.duration * parking_event.lot_rate
    end
    @total.round
  end

  def create
    @parking_events = ParkingEvent.where("license = ?", params[:license]).where(stripe_txn_id: nil).where("time_out IS NOT ?", nil)
    @confirm_total = 0

    @parking_events.each do |parking_event|
      @confirm_total += parking_event.duration * parking_event.lot_rate
    end
    if params[:total].to_i == @confirm_total.round
      Payment::ChargeStripeToken.new(token:          params[:stripe_card_token],
                                    total:          params[:total],
                                    license:        params[:license],
                                    parking_events: @parking_events).call
      #email receipt
      redirect_to root_path, notice: "Thank you, your payment has been received. An receipt has been emailed to you."
    else
      redirect_to root_path, alert: "Error, could not process request, please try again."
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def create
    build_resource(sign_up_params)
    @user = resource
    service = Registration::CreateStripeCustomer.new(user: @user, stripe_token: params[:user][:customer_id])
    if service.call
      resource = @user
      resource_saved = resource.save
    else
      @error_message = "Sorry! The transaction was not completed."
      return render :new
    end
    yield resource if block_given?
    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end
      respond_with resource
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parking_events_helper.rb
module ParkingEventsHelper

  def parse_license(picture_path)
    e = Tesseract::Engine.new {|e|
    e.language  = :eng
    e.blacklist = '|'
    }
    e.text_for(picture_path).strip
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/charges/create.html.slim
h2 Thanks, you paid <strong>$5.00</strong>!

app/views/charges/index.html.slim
h1 Worked. I think.

app/views/charges/new.html.slim
= form_tag charges_path do
  article
    label.amount
      span
        | Amount: $5.00
  script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="#{Rails.configuration.stripe[:publishable_key]}" data-description="A month's subscription" data-amount="500"

app/views/home/index.html.slim
.row
  .col-md-12
    .well
      .row
        H4 Available Parking
      .row
        .bs-example
          #map style='width: 100%; height: 400px;'

.row
  .col-md-6 id='front-div-right'
    .well 
      h4 To have your parking automatically paid for using your credit card, please
      = link_to "Click here", new_user_registration_path, class: "btn btn-primary"

  .col-md-6 id='front-div-left'
    .well
      h4 If you have already parked, please enter your license plate below.
      = form_tag payments_path, method: :get
        .form-group
          = label_tag :license, "License Plate:"
          = text_field_tag :license, nil, class: 'form-control'
          br
          = submit_tag "Search", class: "btn btn-primary"
javascript:
  handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(#{raw @hash.to_json});
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(13);
    });

app/views/home/what.html.slim
h1 Whaaaat.

app/views/layouts/application.html.slim
doctype html
html
  head
    title The Parking Project
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"
    script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'
    script type="text/javascript" src="https://js.stripe.com/v2/"
    = tag :meta, name: "stripe-key", content: ENV["PUBLISHABLE_KEY"]
    = csrf_meta_tags

  body

    nav.navbar.navbar-default role="navigation"
      .container
        .navbar-header
          = link_to "The Parking Project", root_path, class: "navbar-brand"
          ul.nav.navbar-nav
            - if user_signed_in?
              li= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path
              li= link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              li= link_to "Sign In", new_user_session_path

    .container
      - if flash[:notice]
        .alert.alert-success= flash[:notice]
      - elsif flash[:alert]
        .alert.alert-danger= flash[:alert]

      = yield

app/views/layouts/charges.html.slim
DOCTYPE html
html
  head
  body
    = yield

app/views/parking_events/charges.html.slim
doctype html
html
  head

  body
    = yield

app/views/parking_events/create.html.slim
p Existing Event? #{@existing_event.license}

p New Event? #{@new_event.license}
/ = @existing_event.time_in
/ = @existing_event.time_out
/ = @existing_event.photo_in
/ = @existing_event.photo_out

app/views/parking_events/new.html.slim
= form_for @parking_event, authenticity_token: false do |f|
  .form-group
    = f.label :photo_in
    = f.file_field :photo_in
  .form-group
    = f.label :lot_id
    = f.text_field :lot_id
  .form-group
    = f.label :time_in
    = f.datetime_select :time_in

  = f.submit class: "btn btn-primary btn-jumbo"

app/views/parking_events/old_new.html.slim
= form_tag(parking_events_path, method: "post") do 
  .form-group
    = label_tag :photo, "Photo"
    = file_field_tag :photo
  .form-group
    = label_tag :lot_id, "Lot ID"
    = text_field_tag :lot_id

  = submit_tag "Submit"

app/views/payments/index.html.slim
h1 Total balance Owing Against #{@license}: #{number_to_currency (@total.round / 100)}

= simple_form_for "", url: payments_path, html: {id: "token-form"} do |f|
  = f.input :stripe_card_token, as: :hidden
  = f.input :total, as: :hidden, input_html: { value: @total.round }
  = f.input :license, as: :hidden, input_html: { value: @license }

- if @total > 0
  #stripe-errors= @error_message
  = simple_form_for "", html: {id: "cc-form"} do |f|
    = f.input :card_number
    .form-group
      = f.label :expiry_date
      = select_month nil, {add_month_numbers: true}, {class: "form-control"}
      = select_year nil, {start_year: Date.today.year, end_year: Date.today.year + 10}, {class: "form-control"}
    = f.input :cvc
    = f.input :email
    noscript JavaScript must be enabled for this payment to make payment.
    = f.button :submit, value: "Submit Payment", class: "btn btn-primary"
- else
  p No balance is owed against this license. Please click home link at the top left of the page to return to the homepage. 